-- YouTube Analytics Project - Environment Setup

-- Create database
CREATE DATABASE IF NOT EXISTS YOUTUBE_ANALYTICS;
USE DATABASE YOUTUBE_ANALYTICS;

-- Create schemas for different data layers
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS DWH;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- Create warehouses for different workloads
CREATE WAREHOUSE IF NOT EXISTS YOUTUBE_LOAD_WH 
  WITH WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 60 
  AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS YOUTUBE_TRANSFORM_WH 
  WITH WAREHOUSE_SIZE = 'SMALL' 
  AUTO_SUSPEND = 60 
  AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS YOUTUBE_ANALYTICS_WH 
  WITH WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 60 
  AUTO_RESUME = TRUE;

-- Create file formats for data loading
CREATE OR REPLACE FILE FORMAT RAW.CSV_FORMAT
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('NULL', 'null', '')
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE FILE FORMAT RAW.JSON_FORMAT
  TYPE = 'JSON'
  STRIP_OUTER_ARRAY = TRUE;

-- Create stage for external files
CREATE OR REPLACE STAGE RAW.YOUTUBE_EXTERNAL_STAGE
  FILE_FORMAT = RAW.CSV_FORMAT;

-- Create role for the project
CREATE ROLE IF NOT EXISTS YOUTUBE_ANALYTICS_ROLE;
GRANT USAGE ON DATABASE YOUTUBE_ANALYTICS TO ROLE YOUTUBE_ANALYTICS_ROLE;
GRANT USAGE ON SCHEMA YOUTUBE_ANALYTICS.RAW TO ROLE YOUTUBE_ANALYTICS_ROLE;
GRANT USAGE ON SCHEMA YOUTUBE_ANALYTICS.STAGING TO ROLE YOUTUBE_ANALYTICS_ROLE;
GRANT USAGE ON SCHEMA YOUTUBE_ANALYTICS.DWH TO ROLE YOUTUBE_ANALYTICS_ROLE;
GRANT USAGE ON SCHEMA YOUTUBE_ANALYTICS.ANALYTICS TO ROLE YOUTUBE_ANALYTICS_ROLE;
GRANT USAGE ON WAREHOUSE YOUTUBE_LOAD_WH TO ROLE YOUTUBE_ANALYTICS_ROLE;
GRANT USAGE ON WAREHOUSE YOUTUBE_TRANSFORM_WH TO ROLE YOUTUBE_ANALYTICS_ROLE;
GRANT USAGE ON WAREHOUSE YOUTUBE_ANALYTICS_WH TO ROLE YOUTUBE_ANALYTICS_ROLE;

-- Grant additional privileges
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT ON SCHEMA YOUTUBE_ANALYTICS.RAW TO ROLE YOUTUBE_ANALYTICS_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA YOUTUBE_ANALYTICS.STAGING TO ROLE YOUTUBE_ANALYTICS_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA YOUTUBE_ANALYTICS.DWH TO ROLE YOUTUBE_ANALYTICS_ROLE;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA YOUTUBE_ANALYTICS.ANALYTICS TO ROLE YOUTUBE_ANALYTICS_ROLE;

-- Create audit table for pipeline monitoring
CREATE TABLE IF NOT EXISTS YOUTUBE_ANALYTICS.RAW.PIPELINE_LOG (
  PIPELINE_RUN_ID NUMBER IDENTITY(1,1),
  PIPELINE_NAME VARCHAR(100),
  STEP_NAME VARCHAR(100),
  STATUS VARCHAR(20),
  RECORDS_PROCESSED NUMBER,
  ERROR_MESSAGE VARCHAR(1000),
  START_TIME TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  END_TIME TIMESTAMP_LTZ,
  DURATION_SECONDS NUMBER
);

-- Grant privileges on the audit table
GRANT SELECT, INSERT, UPDATE ON TABLE YOUTUBE_ANALYTICS.RAW.PIPELINE_LOG TO ROLE YOUTUBE_ANALYTICS_ROLE;
