-- YouTube Analytics Project - Multi-Environment Setup
-- This script creates DEV, TEST, and PROD environments

-- Create Development Environment
CREATE DATABASE IF NOT EXISTS YOUTUBE_ANALYTICS_DEV;

-- Create Test Environment
CREATE DATABASE IF NOT EXISTS YOUTUBE_ANALYTICS_TEST;

-- Create Production Environment
CREATE DATABASE IF NOT EXISTS YOUTUBE_ANALYTICS_PROD;

-- Create Roles for Environment Access
CREATE ROLE IF NOT EXISTS YOUTUBE_DEV_ROLE;
CREATE ROLE IF NOT EXISTS YOUTUBE_TEST_ROLE;
CREATE ROLE IF NOT EXISTS YOUTUBE_PROD_ROLE;
CREATE ROLE IF NOT EXISTS YOUTUBE_ANALYST_ROLE;

-- Grant privileges to roles
GRANT ALL ON DATABASE YOUTUBE_ANALYTICS_DEV TO ROLE YOUTUBE_DEV_ROLE;
GRANT ALL ON DATABASE YOUTUBE_ANALYTICS_TEST TO ROLE YOUTUBE_TEST_ROLE;
GRANT ALL ON DATABASE YOUTUBE_ANALYTICS_PROD TO ROLE YOUTUBE_PROD_ROLE;

-- Grant read access to analyst role
GRANT USAGE ON DATABASE YOUTUBE_ANALYTICS_PROD TO ROLE YOUTUBE_ANALYST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE YOUTUBE_ANALYTICS_PROD TO ROLE YOUTUBE_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE YOUTUBE_ANALYTICS_PROD TO ROLE YOUTUBE_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE YOUTUBE_ANALYTICS_PROD TO ROLE YOUTUBE_ANALYST_ROLE;

-- Grant read access to test role on dev
GRANT USAGE ON DATABASE YOUTUBE_ANALYTICS_DEV TO ROLE YOUTUBE_TEST_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE YOUTUBE_ANALYTICS_DEV TO ROLE YOUTUBE_TEST_ROLE;
GRANT SELECT ON ALL TABLES IN DATABASE YOUTUBE_ANALYTICS_DEV TO ROLE YOUTUBE_TEST_ROLE;
GRANT SELECT ON ALL VIEWS IN DATABASE YOUTUBE_ANALYTICS_DEV TO ROLE YOUTUBE_TEST_ROLE;

-- Create environment-specific warehouses
CREATE WAREHOUSE IF NOT EXISTS YOUTUBE_DEV_WH 
  WAREHOUSE_SIZE = 'XSMALL' 
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS YOUTUBE_TEST_WH 
  WAREHOUSE_SIZE = 'SMALL' 
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS YOUTUBE_PROD_WH 
  WAREHOUSE_SIZE = 'MEDIUM' 
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- Grant warehouse usage
GRANT USAGE ON WAREHOUSE YOUTUBE_DEV_WH TO ROLE YOUTUBE_DEV_ROLE;
GRANT USAGE ON WAREHOUSE YOUTUBE_TEST_WH TO ROLE YOUTUBE_TEST_ROLE;
GRANT USAGE ON WAREHOUSE YOUTUBE_PROD_WH TO ROLE YOUTUBE_PROD_ROLE;
GRANT USAGE ON WAREHOUSE YOUTUBE_PROD_WH TO ROLE YOUTUBE_ANALYST_ROLE;

-- Create schemas in each environment
USE DATABASE YOUTUBE_ANALYTICS_DEV;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS DWH;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

USE DATABASE YOUTUBE_ANALYTICS_TEST;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS DWH;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

USE DATABASE YOUTUBE_ANALYTICS_PROD;
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS DWH;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- Log the environment setup
USE DATABASE YOUTUBE_ANALYTICS_DEV;
CALL RAW.LOG_PIPELINE_STEP(
  'SETUP', 
  'CREATE_ENVIRONMENTS', 
  'SUCCESS', 
  3, -- Number of environments created
  NULL
);
