-- Update the refresh task to only refresh the valid materialized view

USE DATABASE YOUTUBE_ANALYTICS;
USE SCHEMA RAW;
USE WAREHOUSE YOUTUBE_ANALYTICS_WH;

-- Drop the existing task if it exists
DROP TASK IF EXISTS RAW.REFRESH_ANALYTICS_VIEWS;

-- Create a task to refresh analytics views
CREATE OR REPLACE TASK RAW.REFRESH_ANALYTICS_VIEWS
  WAREHOUSE = YOUTUBE_ANALYTICS_WH
  AFTER RAW.RUN_DATA_QUALITY
AS
BEGIN
  -- Refresh only the valid materialized view
 -- ALTER MATERIALIZED VIEW ANALYTICS.CATEGORY_METRICS REFRESH;
  
  -- Log completion
  INSERT INTO RAW.PIPELINE_LOG (PIPELINE_NAME, STEP_NAME, STATUS, RECORDS_PROCESSED, ERROR_MESSAGE)
  VALUES ('ANALYTICS_REFRESH', 'REFRESH_VIEWS', 'SUCCESS', 0, NULL);
END;

-- Enable the new task
ALTER TASK RAW.REFRESH_ANALYTICS_VIEWS RESUME;
